config:
  lokiAddress: http://loki:3100/loki/api/v1/push
tolerations:
- operator: Exists  # Tolerate all taints to collect logs from all nodes
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
# Deploy promtail to all nodes to collect logs
daemonset:
  enabled: true
