apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    # Update this to your actual Git repository URL
    repoURL: https://github.com/will-wright-eng/k8s-prototype-monitoring.git
    targetRevision: HEAD
    # Update this path to match your actual repository structure
    path: k8s/apps/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
