loki:
  auth_enabled: false

  storage:
    type: filesystem

  limits_config:
    retention_period: 168h  # 7 days
persistence:
  enabled: true
  size: 20Gi
nodeSelector:
  node-type: monitoring
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "monitoring"
  effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "node-type"
          operator: "In"
          values:
          - "monitoring"
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
service:
  type: ClusterIP
